application: namebench
version: 3
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /media
  static_dir: media

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin


- url: .*
  script: main.py

