application: namebench
version: 3
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: .*
  script: main.py

